name: Scrape Google Drive (no API)

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch: {}
  push:
    paths:
      - "scrape.js"
      - ".github/workflows/scrape-drive.yml"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install puppeteer@22

      - name: Run scraper
        env:
          DRIVE_FOLDER_URL: ${{ secrets.DRIVE_FOLDER_URL }}
        run: node scrape.js "$DRIVE_FOLDER_URL"

      - name: Commit files.json
        run: |
          if [[ -n "$(git status --porcelain files.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add files.json
            git commit -m "Update files.json from Drive (scraped)"
            git push
          else
            echo "No changes."
          fi
